# Element-wise operations

In [1]:
import numpy

In [2]:
a = numpy.ones( [4,4] )
a

array([[ 1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.]])

In [3]:
b = numpy.ones( [4,4] )
b

array([[ 1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.]])

#### The following instructions computes the element-wise product. Not the dot product.

In [7]:
a*b #Ha hecho la multiplicacion de las matrices, elemento a elemento

array([[ 1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.]])

#### If we need the dot product we have to use the proper function.

In [8]:
numpy.dot( a, b ) #Si son de dimensiones compatibles, 'dot' hará el producto escalar

array([[ 4.,  4.,  4.,  4.],
       [ 4.,  4.,  4.,  4.],
       [ 4.,  4.,  4.,  4.],
       [ 4.,  4.,  4.,  4.]])

In [9]:
a.dot(b)

array([[ 4.,  4.,  4.,  4.],
       [ 4.,  4.,  4.,  4.],
       [ 4.,  4.,  4.,  4.],
       [ 4.,  4.,  4.,  4.]])

### Creating n-dimensional arrays of random numbers.

#### In the range [0,1[

In [12]:
x = numpy.random.rand( 5, 5 ) #Matriz de 5x5
x

array([[ 0.08724773,  0.82668697,  0.46723169,  0.88800923,  0.41370249],
       [ 0.80513294,  0.95774741,  0.34893667,  0.701983  ,  0.93865438],
       [ 0.13575829,  0.00399638,  0.55639636,  0.97024772,  0.92514423],
       [ 0.69854645,  0.22063588,  0.77293128,  0.74136683,  0.01210454],
       [ 0.52431339,  0.51680234,  0.66644917,  0.60957963,  0.96760638]])

In [13]:
numpy.exp( x )

array([[ 1.09116696,  2.28573348,  1.59557104,  2.4302867 ,  1.51240711],
       [ 2.23699386,  2.60582001,  1.41755941,  2.01774994,  2.55653896],
       [ 1.145405  ,  1.00400438,  1.74437506,  2.63859801,  2.52223201],
       [ 2.01082775,  1.24686934,  2.16610642,  2.09880226,  1.0121781 ],
       [ 1.68929855,  1.67665768,  1.94731047,  1.83965791,  2.63163778]])

#### Or normally distributed values, with zero mean and variance one.

In [16]:
x = numpy.random.randn( 5, 5 )
x

array([[ -1.45441500e+00,   1.12460379e+00,  -4.22038384e-01,
         -3.13346980e-01,   1.16937073e-01],
       [  6.12795066e-01,  -2.26880609e+00,   5.49096325e-01,
          8.55878662e-01,  -1.64032825e+00],
       [ -8.51027984e-01,   5.33929641e-01,  -2.80947314e-01,
         -2.69785672e-01,  -8.21797391e-01],
       [ -5.17702575e-01,   1.82783641e-01,  -5.34479421e-01,
          1.45654634e-03,   2.08903624e-01],
       [ -1.18491462e-01,  -2.36928080e-01,  -2.63283066e-01,
          5.05221335e-01,   7.67540699e-01]])

In [17]:
numpy.exp( x )

array([[ 0.23353694,  3.07899667,  0.65570887,  0.73099623,  1.12404869],
       [ 1.84558272,  0.1034356 ,  1.73168743,  2.35344135,  0.19391638],
       [ 0.42697578,  1.70562164,  0.75506812,  0.76354313,  0.43964074],
       [ 0.59588798,  1.20055463,  0.58597426,  1.00145761,  1.23232623],
       [ 0.8882594 ,  0.78904803,  0.76852432,  1.65735231,  2.15446126]])

In [18]:
x = x * 10
x

array([[ -1.45441500e+01,   1.12460379e+01,  -4.22038384e+00,
         -3.13346980e+00,   1.16937073e+00],
       [  6.12795066e+00,  -2.26880609e+01,   5.49096325e+00,
          8.55878662e+00,  -1.64032825e+01],
       [ -8.51027984e+00,   5.33929641e+00,  -2.80947314e+00,
         -2.69785672e+00,  -8.21797391e+00],
       [ -5.17702575e+00,   1.82783641e+00,  -5.34479421e+00,
          1.45654634e-02,   2.08903624e+00],
       [ -1.18491462e+00,  -2.36928080e+00,  -2.63283066e+00,
          5.05221335e+00,   7.67540699e+00]])

In [19]:
numpy.exp( x )

array([[  4.82565094e-07,   7.65759145e+04,   1.46930037e-02,
          4.35663682e-02,   3.21996578e+00],
       [  4.58495585e+02,   1.40184616e-10,   2.42490675e+02,
          5.21235276e+03,   7.51873791e-08],
       [  2.01387461e-04,   2.08366054e+02,   6.02367203e-02,
          6.73497072e-02,   2.69761071e-04],
       [  5.64477044e-03,   6.22041369e+00,   4.77293334e-03,
          1.01467206e+00,   8.07712698e+00],
       [  3.05772285e-01,   9.35479820e-02,   7.18747208e-02,
          1.56368179e+02,   2.15470045e+03]])

In [20]:
x = numpy.random.randn( 2, 5 )
x

array([[ 0.08045453,  0.32845961,  0.09013708,  0.47825055, -1.405315  ],
       [-3.47788178, -0.61898843,  1.64270148,  0.98096229,  2.10950216]])

In [21]:
x.dtype

dtype('float64')

In [22]:
y = x.astype( 'f' )
y

array([[ 0.08045453,  0.32845962,  0.09013708,  0.47825053, -1.40531504],
       [-3.47788167, -0.61898845,  1.64270151,  0.98096228,  2.10950208]], dtype=float32)

In [23]:
y.dtype

dtype('float32')

In [24]:
x.transpose() #Matriz traspuesta

array([[ 0.08045453, -3.47788178],
       [ 0.32845961, -0.61898843],
       [ 0.09013708,  1.64270148],
       [ 0.47825055,  0.98096229],
       [-1.405315  ,  2.10950216]])