# Basic statistics

In [1]:
import numpy

In [2]:
x = numpy.random.randn( 1000 ) * 5 + 10 #Hemos generado 1000 valores aleatorios
# x # uncomment this line for showing the contents of 'x'.

In [3]:
x.sum()

10247.113452799094

In [4]:
x.mean() #media

10.247113452799095

In [5]:
x.std() #desviacion tipica

4.9588333103022419

In [7]:
x.var() #varianza

24.590027799363089

In [9]:
numpy.cov(x) #devuelve tambien la varianza

array(24.614642441804893)

In [11]:
y = numpy.random.randn( 1000 ) * 3 - 7 # desviacion 3, media 7
# y # uncomment this line for showing the contents of 'y'.

In [14]:
xy = numpy.vstack( [ x, y ] ) #Apilado vertical de x e y
xy

array([[ 16.38558049,  22.52413627,  13.22551409, ...,   1.9098074 ,
          4.14139678,  19.61373097],
       [-10.198995  , -10.89514651,  -4.84837011, ..., -10.52643918,
        -11.62787592,  -7.32551684]])

In [15]:
numpy.cov(xy)

array([[ 24.61464244,  -0.82985652],
       [ -0.82985652,   8.19999257]])

In [18]:
xy = numpy.random.multivariate_normal( [7,5], [[36,-9],[-9,49]], 10000 )
#Vector de medias, matriz de variantes y covarianzas, y genera 10,000 elementos (muestras)

In [19]:
xy.sum(axis=0) #Suma de elementos de la primera dimensión por separado

array([ 69988.17535531,  49612.26337165])

In [20]:
xy.mean(axis=0)

array([ 6.99881754,  4.96122634])

In [21]:
xy.std(axis=0)

array([ 5.97927812,  7.03682787])

In [22]:
xy.var(axis=0)

array([ 35.75176678,  49.51694643])

In [23]:
numpy.cov(xy.transpose())

array([[ 35.75534232,  -9.46626322],
       [ -9.46626322,  49.52189862]])

In [24]:
# Create an array of random values in [0,100[
x = numpy.random.rand( 10000 ) * 100
x

array([ 71.19646228,  10.94764812,  59.37293972, ...,  84.16910064,
         3.98210011,  85.30247753])

In [25]:
# Remove decimals and convert to integer
x = numpy.floor(x).astype( 'i' )
# Show the final array of ints
print( x )

[71 10 59 ..., 84  3 85]


In [27]:
# Compute the counters
bc = numpy.bincount( x ) # 'bincount' Permite contabilizar los números enteros que aparecen en el array original
# Show the counters
print( bc )

[ 96 100  81 102  98 115  96  88  94  94  99 109  86  98 117 100 104  96
  93  99 109 108 102  93 101 111 109  91 101 116  85  92  85  94 106  99
  92 101 103  99  91 111  97 114 111  94  93  86  99 102 118  98 125 101
 108 105  76 112  92  94  97 102 102  83 104 109  89 107 105  74 102 105
 114  97 130  90  84  89 101  85 101 100  92 120  95 102  91 101  94  92
 109  94 117 111 108 105  84 108 112 106]


## Histograms

In [28]:
x = numpy.random.rand( 10000 ) * 100
hist,bin_edges = numpy.histogram( x, bins=20, density=False )
print( hist )

[514 479 504 477 487 476 529 484 480 553 540 470 506 523 517 463 505 491
 499 503]


In [29]:
hist,bin_edges = numpy.histogram( x, bins=20, density=True )
print( hist )
print( bin_edges ) # The same in both cases

[ 0.01028169  0.00958157  0.01008165  0.00954156  0.0097416   0.00952156
  0.01058174  0.00968159  0.00960157  0.01106181  0.01080177  0.00940154
  0.01012166  0.01046172  0.0103417   0.00926152  0.01010166  0.00982161
  0.00998164  0.01006165]
[  9.47963486e-03   5.00865981e+00   1.00078400e+01   1.50070202e+01
   2.00062004e+01   2.50053805e+01   3.00045607e+01   3.50037409e+01
   4.00029211e+01   4.50021012e+01   5.00012814e+01   5.50004616e+01
   5.99996418e+01   6.49988220e+01   6.99980021e+01   7.49971823e+01
   7.99963625e+01   8.49955427e+01   8.99947229e+01   9.49939030e+01
   9.99930832e+01]
