# Basic Linear Algebra

In [1]:
import numpy

In [2]:
a = numpy.ones( 5 )
a

array([ 1.,  1.,  1.,  1.,  1.])

In [3]:
b = numpy.ones( 4 )*2
b

array([ 2.,  2.,  2.,  2.])

### Scalar or dot product.

In [4]:
numpy.dot( a, a )

5.0

### Inner product. The same 

In [5]:
numpy.inner( a, a )

5.0

### Outer product, also known as external product.

In [8]:
numpy.outer( a, b )

array([[ 2.,  2.,  2.,  2.],
       [ 2.,  2.,  2.,  2.],
       [ 2.,  2.,  2.,  2.],
       [ 2.,  2.,  2.,  2.],
       [ 2.,  2.,  2.,  2.]])

In [9]:
c = numpy.array( [ [9,-3], [-3,9] ] ) #Creamos un array de 2x2, cuyo valores los asignamos nosotros
c

array([[ 9, -3],
       [-3,  9]])

## Determinants.

In [10]:
numpy.linalg.det( c )

72.0

In [12]:
sign,log_det = numpy.linalg.slogdet( c ) # te devuelve el signo del determimante, y el logaritmo del determimnante por otro lado
sign * numpy.exp( log_det )

#Hace lo mismo que el de arriba, pero este método es más fiable

72.0

## Matrix inverse.

In [13]:
numpy.linalg.inv( c ) # 'inv' inversa

array([[ 0.125     ,  0.04166667],
       [ 0.04166667,  0.125     ]])

In [16]:
#help(numpy.linalg.pinv) => si descomentamos, nos mostrará la ayuda
numpy.linalg.pinv( c ) # 'pinv' pseudo-inversa

array([[ 0.125     ,  0.04166667],
       [ 0.04166667,  0.125     ]])

## Cholesky decomposition.

In [17]:
c = numpy.array( [ [9,-3], [-3,9] ] )
c

array([[ 9, -3],
       [-3,  9]])

In [18]:
L = numpy.linalg.cholesky(c)
L

array([[ 3.        ,  0.        ],
       [-1.        ,  2.82842712]])

### Performing sanity checks is useful for avoiding unexpected results.

In [24]:
print( "sanity check" ) #Comprueba si las operaciones realiazadas comcuerdan con la original
numpy.dot( L, L.T.conj() )

sanity check


array([[ 9., -3.],
       [-3.,  9.]])

## QR decomposition.

In [25]:
q,r, = numpy.linalg.qr( c, mode='full' ) #Matriz descompuesta
print( "q" )
print( q )
print( "r" )
print( r )

q
[[-0.9486833   0.31622777]
 [ 0.31622777  0.9486833 ]]
r
[[-9.48683298  5.69209979]
 [ 0.          7.58946638]]


In [26]:
print( "sanity check" )
print( q.dot(r) )

sanity check
[[ 9. -3.]
 [-3.  9.]]


## Singular Valude Decomposition (SVD)

###### (No hay que saberlo, solo saber que está)

In [27]:
U,s,V = numpy.linalg.svd( c )
print( "U.shape " + str(U.shape) )
print( "s.shape " + str(s.shape) )
print( "V.shape " + str(V.shape) )

U.shape (2, 2)
s.shape (2,)
V.shape (2, 2)


In [28]:
print( "U" )
print( U )
print( "s" )
print( s )
print( "V" )
print( V )

U
[[-0.70710678  0.70710678]
 [ 0.70710678  0.70710678]]
s
[ 12.   6.]
V
[[-0.70710678  0.70710678]
 [ 0.70710678  0.70710678]]


In [29]:
S = numpy.diag(s)
print( "sanity check" )
print( numpy.dot( U, numpy.dot( S, V ) ) )

sanity check
[[ 9. -3.]
 [-3.  9.]]
