# Manipulations

In [1]:
import numpy

In [2]:
x = numpy.random.rand( 5, 5 )
x

array([[ 0.19483525,  0.47082173,  0.13143536,  0.7583133 ,  0.49623273],
       [ 0.50513573,  0.36984402,  0.5947981 ,  0.90581279,  0.59389067],
       [ 0.2870575 ,  0.13690004,  0.47175694,  0.50819508,  0.79544633],
       [ 0.68765865,  0.36026089,  0.83076511,  0.11338402,  0.49463561],
       [ 0.12603637,  0.32560085,  0.48177952,  0.77671341,  0.94196754]])

### Getting the diagonal of a matrix.

In [6]:
numpy.diag( x ) # 'diag' Recoge los valores de la diagonal y te los muestra en un array

array([ 0.19483525,  0.36984402,  0.47175694,  0.11338402,  0.94196754])

### Or converting a vector in to a matrix with the original values of the vector in the diagonal.

In [7]:
numpy.diag( numpy.diag( x ) ) #Te devuelve una matriz solo con la diagonal

array([[ 0.19483525,  0.        ,  0.        ,  0.        ,  0.        ],
       [ 0.        ,  0.36984402,  0.        ,  0.        ,  0.        ],
       [ 0.        ,  0.        ,  0.47175694,  0.        ,  0.        ],
       [ 0.        ,  0.        ,  0.        ,  0.11338402,  0.        ],
       [ 0.        ,  0.        ,  0.        ,  0.        ,  0.94196754]])

### Concatenation of arrays in two ways: horizontally or vertically.

###### (Operaciones con mucho coste computacional)

In [12]:
numpy.hstack( [ numpy.diag( x ), numpy.diag( x ) ] ) # 'hstack' Apilado horizontal. El resultado en un Array Unidimensional

array([ 0.19483525,  0.36984402,  0.47175694,  0.11338402,  0.94196754,
        0.19483525,  0.36984402,  0.47175694,  0.11338402,  0.94196754])

In [13]:
numpy.vstack( [ numpy.diag( x ), numpy.diag( numpy.diag( x ) ) ] ) # 'vstack' Apilado vertical. 
# 'numpy.diag( x )' => Array unidimensional de 5 elementos
# 'numpy.diag( numpy.diag( x ) ) ' => Matriz de 5 x 5
# Al apilarlos verticalmente, devuelve una matriz con una fila más.
# Debe ser compatible dimensionalmente

array([[ 0.19483525,  0.36984402,  0.47175694,  0.11338402,  0.94196754],
       [ 0.19483525,  0.        ,  0.        ,  0.        ,  0.        ],
       [ 0.        ,  0.36984402,  0.        ,  0.        ,  0.        ],
       [ 0.        ,  0.        ,  0.47175694,  0.        ,  0.        ],
       [ 0.        ,  0.        ,  0.        ,  0.11338402,  0.        ],
       [ 0.        ,  0.        ,  0.        ,  0.        ,  0.94196754]])

### Useful functions already implemented.

In [14]:
x = numpy.linspace( 100, 1, 100 )
x

array([ 100.,   99.,   98.,   97.,   96.,   95.,   94.,   93.,   92.,
         91.,   90.,   89.,   88.,   87.,   86.,   85.,   84.,   83.,
         82.,   81.,   80.,   79.,   78.,   77.,   76.,   75.,   74.,
         73.,   72.,   71.,   70.,   69.,   68.,   67.,   66.,   65.,
         64.,   63.,   62.,   61.,   60.,   59.,   58.,   57.,   56.,
         55.,   54.,   53.,   52.,   51.,   50.,   49.,   48.,   47.,
         46.,   45.,   44.,   43.,   42.,   41.,   40.,   39.,   38.,
         37.,   36.,   35.,   34.,   33.,   32.,   31.,   30.,   29.,
         28.,   27.,   26.,   25.,   24.,   23.,   22.,   21.,   20.,
         19.,   18.,   17.,   16.,   15.,   14.,   13.,   12.,   11.,
         10.,    9.,    8.,    7.,    6.,    5.,    4.,    3.,    2.,    1.])

In [15]:
x.min() #Muestra el minimo

1.0

In [17]:
x.max() #Muestra el maximo

100.0

In [20]:
x.argmin() #Muestra la posicion del minimo valor

99

In [21]:
x.argmax() #Muestra la posicion del máximo valor

0

In [25]:
x.ptp() # (Point to Point) Diferencia entre el valor mínimo y el valor máximo

99.0


### Sorting in place.

In [26]:
x.sort() #Ordena el propio vector, el original, de mínimo a máximo
x

array([   1.,    2.,    3.,    4.,    5.,    6.,    7.,    8.,    9.,
         10.,   11.,   12.,   13.,   14.,   15.,   16.,   17.,   18.,
         19.,   20.,   21.,   22.,   23.,   24.,   25.,   26.,   27.,
         28.,   29.,   30.,   31.,   32.,   33.,   34.,   35.,   36.,
         37.,   38.,   39.,   40.,   41.,   42.,   43.,   44.,   45.,
         46.,   47.,   48.,   49.,   50.,   51.,   52.,   53.,   54.,
         55.,   56.,   57.,   58.,   59.,   60.,   61.,   62.,   63.,
         64.,   65.,   66.,   67.,   68.,   69.,   70.,   71.,   72.,
         73.,   74.,   75.,   76.,   77.,   78.,   79.,   80.,   81.,
         82.,   83.,   84.,   85.,   86.,   87.,   88.,   89.,   90.,
         91.,   92.,   93.,   94.,   95.,   96.,   97.,   98.,   99.,  100.])