# Introduction to Numpy

## Numpy is the library of Python for working efficiently with arrays.
### It includes a set of subpackages with functions of statistics and linear algebra.

For using a Python package the first step is importing it.
Or importing some subpackages, classes or functions of it.

In [1]:
import numpy

Creates a Numpy array from a list, or list of lists.
In this particular case a two dimensional array is created from a list of lists.
Pay attention to the brackets.

In [2]:
x = numpy.array( [[1,2,3],[4,5,6]], numpy.int32 ) 

Check the type of a variable.

In [3]:
type(x)

numpy.ndarray

Get info about the shape. This provides de number of dimensions and the size of the array in each dimension.

In [4]:
x.shape

(2, 3)

The attribute 'dtype' of Numpy arrays give us information about the data type of the components.
This is different from the result obtained in the command type(x).

In [5]:
x.dtype

dtype('int32')

Which is the data type of array elements when it is not specified?

Does it depends on the values used for initialization?

In [6]:
x = numpy.array( [[1,2,3],[4,5,6]])

In [7]:
type(x)

numpy.ndarray

In [8]:
x.shape

(2, 3)

In [9]:
x.dtype

dtype('int64')

In [10]:
x = numpy.array( [[1,2.0,3],[4,5,6]] ) 

In [11]:
x.shape

(2, 3)

In [12]:
x.dtype

dtype('float64')

In [14]:
x

array([[ 1.,  2.,  3.],
       [ 4.,  5.,  6.]])

### Indexing and slicing.

In [16]:
x[1,2]

6.0

### Work with partial views of arrays.

In [17]:
y=x[:,1]

In [18]:
print(y)

[ 2.  5.]


#### Does the following instruction modify the contents of 'x'?

In [19]:
y[0]=20

In [20]:
y

array([ 20.,   5.])

In [21]:
x

array([[  1.,  20.,   3.],
       [  4.,   5.,   6.]])

In [23]:
x[0:2,1:3] #Es hasta donde quieres llegar -1. El primero es excluyendo, y el segundo es incluyendo

array([[ 20.,   3.],
       [  5.,   6.]])

In [24]:
x = numpy.array( [1,2,3,4,5,6,7,8,9], dtype=int )
x

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

#### Converts an array with elements of one type to another. In this case from int to float.

In [44]:
m1 = x.astype( float )
print(m1)
m1.dtype

[ 1.  2.  3.  4.  5.  6.  7.  8.  9.]


dtype('float64')

Converts a 1-dimensional array into a 2-dimensional one.

In [45]:
m2 = m1.reshape( 3, 3)#.copy()
print(m2)
m2.dtype

[[ 1.  2.  3.]
 [ 4.  5.  6.]
 [ 7.  8.  9.]]


dtype('float64')

In [46]:
m2[1,1] = -999
print (m1)
print (m2)

[   1.    2.    3.    4. -999.    6.    7.    8.    9.]
[[   1.    2.    3.]
 [   4. -999.    6.]
 [   7.    8.    9.]]


Converts a n-dimensional array into a 1-dimensional one.

In [47]:
m3=m2.ravel()
print( m3 )

[   1.    2.    3.    4. -999.    6.    7.    8.    9.]
