# Array creation and initialization

In [1]:
import numpy

### Creating a numpy array with complex numbers.

In [2]:
x = numpy.array( [ [ 1, 2.0 ], [ 0, 0 ], ( 1+1j, 3. ) ] )
x

array([[ 1.+0.j,  2.+0.j],
       [ 0.+0.j,  0.+0.j],
       [ 1.+1.j,  3.+0.j]])

### Generating arrays with values in a range. In this case integers.

In [3]:
numpy.arange( 10 )

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

#### We can force that numpy.arange() returns an array of floating point numbers.

In [5]:
numpy.arange( 2, 10, dtype=numpy.float ) #Empieza en el 2 y termina en el 10 -1, de ahí el 9

array([ 2.,  3.,  4.,  5.,  6.,  7.,  8.,  9.])

#### Or by specifying an increment that is a real value.

In [8]:
numpy.arange( 2, 10, 0.5 ) #El 0.5 es el incremento

array([ 2. ,  2.5,  3. ,  3.5,  4. ,  4.5,  5. ,  5.5,  6. ,  6.5,  7. ,
        7.5,  8. ,  8.5,  9. ,  9.5])

#### Another option is to use numpy.linspace(), that returns arrays with floating point values.

In [18]:
numpy.linspace( 1., 4., 6 ) #linspace, xpaciado lineal

array([ 1. ,  1.6,  2.2,  2.8,  3.4,  4. ])

In [19]:
numpy.linspace( 0., 100., 51 )

array([   0.,    2.,    4.,    6.,    8.,   10.,   12.,   14.,   16.,
         18.,   20.,   22.,   24.,   26.,   28.,   30.,   32.,   34.,
         36.,   38.,   40.,   42.,   44.,   46.,   48.,   50.,   52.,
         54.,   56.,   58.,   60.,   62.,   64.,   66.,   68.,   70.,
         72.,   74.,   76.,   78.,   80.,   82.,   84.,   86.,   88.,
         90.,   92.,   94.,   96.,   98.,  100.])

#### If we need a log scale instead of a linear scale the following method returns it.

In [20]:
numpy.logspace( 1., 100., 12 ) #logspace, xpaciado logaritmicamente, es decir, exponencialmente

array([  1.00000000e+001,   1.00000000e+010,   1.00000000e+019,
         1.00000000e+028,   1.00000000e+037,   1.00000000e+046,
         1.00000000e+055,   1.00000000e+064,   1.00000000e+073,
         1.00000000e+082,   1.00000000e+091,   1.00000000e+100])

#### A special method generates the set of indices to acces n-dimensional arrays. Here an example in two dimensions.

In [25]:
ind = numpy.indices( (3,3) ) #tridimensional. Es un array con dos matrices de 3x3
ind

array([[[0, 0, 0],
        [1, 1, 1],
        [2, 2, 2]],

       [[0, 1, 2],
        [0, 1, 2],
        [0, 1, 2]]])

In [26]:
ind.shape

(2, 3, 3)

#### Following several simple examples for creating arrays.

In [27]:
numpy.zeros( 4 )

array([ 0.,  0.,  0.,  0.])

In [28]:
numpy.zeros( [10,10] )

array([[ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.]])

In [30]:
numpy.zeros( (3,7,5) ) #3 matrices, de 7 filas, de 5 columnas

array([[[ 0.,  0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.,  0.]],

       [[ 0.,  0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.,  0.]],

       [[ 0.,  0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.,  0.]]])

In [32]:
numpy.ones( (6, 6) ) #matriz con valores de 1, de 6 filas x 6 columnas

array([[ 1.,  1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.,  1.]])

In [34]:
numpy.ones( (10,10) ) * numpy.pi #matriz de 10x10, cuyo valores es de 10

array([[ 3.14159265,  3.14159265,  3.14159265,  3.14159265,  3.14159265,
         3.14159265,  3.14159265,  3.14159265,  3.14159265,  3.14159265],
       [ 3.14159265,  3.14159265,  3.14159265,  3.14159265,  3.14159265,
         3.14159265,  3.14159265,  3.14159265,  3.14159265,  3.14159265],
       [ 3.14159265,  3.14159265,  3.14159265,  3.14159265,  3.14159265,
         3.14159265,  3.14159265,  3.14159265,  3.14159265,  3.14159265],
       [ 3.14159265,  3.14159265,  3.14159265,  3.14159265,  3.14159265,
         3.14159265,  3.14159265,  3.14159265,  3.14159265,  3.14159265],
       [ 3.14159265,  3.14159265,  3.14159265,  3.14159265,  3.14159265,
         3.14159265,  3.14159265,  3.14159265,  3.14159265,  3.14159265],
       [ 3.14159265,  3.14159265,  3.14159265,  3.14159265,  3.14159265,
         3.14159265,  3.14159265,  3.14159265,  3.14159265,  3.14159265],
       [ 3.14159265,  3.14159265,  3.14159265,  3.14159265,  3.14159265,
         3.14159265,  3.14159265,  3.14159265

In [35]:
numpy.identity( 10 ) * 99

array([[ 99.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.],
       [  0.,  99.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.],
       [  0.,   0.,  99.,   0.,   0.,   0.,   0.,   0.,   0.,   0.],
       [  0.,   0.,   0.,  99.,   0.,   0.,   0.,   0.,   0.,   0.],
       [  0.,   0.,   0.,   0.,  99.,   0.,   0.,   0.,   0.,   0.],
       [  0.,   0.,   0.,   0.,   0.,  99.,   0.,   0.,   0.,   0.],
       [  0.,   0.,   0.,   0.,   0.,   0.,  99.,   0.,   0.,   0.],
       [  0.,   0.,   0.,   0.,   0.,   0.,   0.,  99.,   0.,   0.],
       [  0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,  99.,   0.],
       [  0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,  99.]])

#### We can load data from files. An example for automatically loading data from text files with comma separated values.

In [39]:
mat = numpy.genfromtxt( 'matrix-001.csv', delimiter=',' ) #carga un fichero CSV
print( mat )

[[ 9.  6.  3.]
 [ 8.  5.  2.]
 [ 7.  4.  1.]]


### Examples of indexing.

In [43]:
x = numpy.arange( 100 ) #el tamaño del array es 100. El -1 es el 99.
print( x[5] ) #de 0 hacia delante, en este caso 5
print( x[-8] ) #de la ultima posicion le quita 8 posiciones.

5
92


In [49]:
y = x.reshape( 10, 10 ) #cambiamos el aspecto con reshape
print( y[5,5] ) #Fila 5, columna 5
print( y[-1,-1] ) #El elemento de la última columna de la última fila

55
99


In [50]:
x[5:9]

array([5, 6, 7, 8])

In [51]:
x[70:-10] #Como empieza en el -99, le quitamos 10, y es 89

array([70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86,
       87, 88, 89])

In [53]:
x[5:20:3] #Va saltando de 3 en 3 por el array

array([ 5,  8, 11, 14, 17])

In [57]:
y[3:6,7:] #Coge fila 3, fila 4 y fila 5. Y columnas de la 7 hasta el final (coge la fila 7, 8 y 9)

array([[37, 38, 39],
       [47, 48, 49],
       [57, 58, 59]])

In [60]:
y[ :6,7:] #Coge filas de la 0 a la 5. Y columnas de la 7 al final

array([[ 7,  8,  9],
       [17, 18, 19],
       [27, 28, 29],
       [37, 38, 39],
       [47, 48, 49],
       [57, 58, 59]])

### Selective indexing. (Idexado o filtrado por contenido)

In [67]:
x[ x%2 == 0 ] #Indexa por valores de x de 2 en 2


array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32,
       34, 36, 38, 40, 42, 44, 46, 48, 50, 52, 54, 56, 58, 60, 62, 64, 66,
       68, 70, 72, 74, 76, 78, 80, 82, 84, 86, 88, 90, 92, 94, 96, 98])

In [74]:
y[ y%2 != 0 ] #Si indexamos por la y, lo hace al reves que x. Mostrará todos los valores menos los que le dices en x, para entenderlo mejor

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33,
       35, 37, 39, 41, 43, 45, 47, 49, 51, 53, 55, 57, 59, 61, 63, 65, 67,
       69, 71, 73, 75, 77, 79, 81, 83, 85, 87, 89, 91, 93, 95, 97, 99])

In [78]:
r = numpy.random.rand( 10, 10 ) #array de 10x10, con valores aleatorios

In [79]:
r

array([[ 0.86252888,  0.93410384,  0.30198587,  0.52136274,  0.84993623,
         0.32018133,  0.53549677,  0.54067209,  0.8673979 ,  0.01737352],
       [ 0.98301378,  0.24163028,  0.05782246,  0.93179339,  0.78173692,
         0.01306423,  0.45740383,  0.42169654,  0.37729346,  0.10778432],
       [ 0.70658963,  0.24264036,  0.94553749,  0.09248839,  0.49749833,
         0.2703967 ,  0.25039012,  0.97534232,  0.97879237,  0.94337804],
       [ 0.65370221,  0.74980577,  0.82247129,  0.35019726,  0.21274655,
         0.67469869,  0.01606175,  0.99166522,  0.5039172 ,  0.47551759],
       [ 0.97157676,  0.21872001,  0.88136726,  0.11748198,  0.78431035,
         0.17028609,  0.64341605,  0.31131124,  0.59162789,  0.06954773],
       [ 0.88821736,  0.90170101,  0.3771883 ,  0.70787657,  0.02712686,
         0.34431719,  0.11709306,  0.32435136,  0.43249402,  0.66943754],
       [ 0.33043144,  0.59747706,  0.36588288,  0.59244104,  0.65457368,
         0.53327614,  0.30323916,  0.14028604

In [84]:
r[ r > 0.5 ] = 1.0 #Tomando los valores aleatorios de r, Si r son mayores que 0.5 los pones a 1

In [85]:
r[ r <= 0.5 ] = -1.0 #Si r es menor que 0.5 lo pones a -1

In [86]:
r

array([[ 1.,  1., -1.,  1.,  1., -1.,  1.,  1.,  1., -1.],
       [ 1., -1., -1.,  1.,  1., -1., -1., -1., -1., -1.],
       [ 1., -1.,  1., -1., -1., -1., -1.,  1.,  1.,  1.],
       [ 1.,  1.,  1., -1., -1.,  1., -1.,  1.,  1., -1.],
       [ 1., -1.,  1., -1.,  1., -1.,  1., -1.,  1., -1.],
       [ 1.,  1., -1.,  1., -1., -1., -1., -1., -1.,  1.],
       [-1.,  1., -1.,  1.,  1.,  1., -1., -1.,  1.,  1.],
       [-1., -1.,  1.,  1.,  1., -1.,  1., -1.,  1., -1.],
       [ 1., -1.,  1.,  1., -1.,  1., -1., -1., -1., -1.],
       [-1., -1.,  1.,  1., -1.,  1., -1.,  1.,  1., -1.]])

### Structural indexing.

In [88]:
z = numpy.ones( [ 5, 7 ] ) #Arra de 2 dimensiones, de 5 filas x 7 columnas

In [90]:
z.shape #tamaño de 5x7

(5, 7)

In [91]:
z2 = z[:,numpy.newaxis,:]

In [92]:
z2.shape

(5, 1, 7)

In [93]:
z

array([[ 1.,  1.,  1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.,  1.,  1.]])

In [96]:
z2 #5 filas, 1 columna, y profundidad 7

array([[[ 1.,  1.,  1.,  1.,  1.,  1.,  1.]],

       [[ 1.,  1.,  1.,  1.,  1.,  1.,  1.]],

       [[ 1.,  1.,  1.,  1.,  1.,  1.,  1.]],

       [[ 1.,  1.,  1.,  1.,  1.,  1.,  1.]],

       [[ 1.,  1.,  1.,  1.,  1.,  1.,  1.]]])

#### Creating a new dimension over an existing array.

In [97]:
x = numpy.arange( 81 ).reshape(3,3,3,3) #Creamos un Array de 4 dimensiones


In [98]:
x

array([[[[ 0,  1,  2],
         [ 3,  4,  5],
         [ 6,  7,  8]],

        [[ 9, 10, 11],
         [12, 13, 14],
         [15, 16, 17]],

        [[18, 19, 20],
         [21, 22, 23],
         [24, 25, 26]]],


       [[[27, 28, 29],
         [30, 31, 32],
         [33, 34, 35]],

        [[36, 37, 38],
         [39, 40, 41],
         [42, 43, 44]],

        [[45, 46, 47],
         [48, 49, 50],
         [51, 52, 53]]],


       [[[54, 55, 56],
         [57, 58, 59],
         [60, 61, 62]],

        [[63, 64, 65],
         [66, 67, 68],
         [69, 70, 71]],

        [[72, 73, 74],
         [75, 76, 77],
         [78, 79, 80]]]])

In [100]:
x[1,1,1,1] #ACORDARSE QUE SIEMPRE EMPIEZA EN 0

40

In [102]:
x[1,...,2] #De la matriz con posicion 1, vemos las columnas con la posicion 2

array([[29, 32, 35],
       [38, 41, 44],
       [47, 50, 53]])

In [104]:
x[1,:,:,2] #Es lo mismo de arriba, pero hecho de otra forma

array([[29, 32, 35],
       [38, 41, 44],
       [47, 50, 53]])

#### Assigning values to a subrange.

In [109]:
x = numpy.ones( [10,10] ) #Matriz de 10x10, cuyo valores es 1

In [110]:
x

array([[ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.]])

In [111]:
x[:3,7:] = 8 #Ponemos valor 8 en las posiciones que le ponemos. Es de decir, en las 3 primeras filas, y de la columna 7 hasta el final

In [112]:
x

array([[ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  8.,  8.,  8.],
       [ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  8.,  8.,  8.],
       [ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  8.,  8.,  8.],
       [ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.]])

### Broadcasting.

In [115]:
a = numpy.ones( (4,4) ) #Columna de 4 x 4
a

array([[ 1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.]])

In [116]:
b = numpy.ones( 4 ) * 3 #Vector columna de 4 columnas cuyo valor es 3
b

array([ 3.,  3.,  3.,  3.])

In [117]:
a+b

array([[ 4.,  4.,  4.,  4.],
       [ 4.,  4.,  4.,  4.],
       [ 4.,  4.,  4.,  4.],
       [ 4.,  4.,  4.,  4.]])

In [118]:
b = numpy.ones( 3 ) * 3
b

array([ 3.,  3.,  3.])

In [120]:
a+b #Dimensiones no compatibles, por eso da ERROR

ValueError: operands could not be broadcast together with shapes (4,4) (3,) 

In [122]:
a = numpy.linspace( 10, 100, 10 ) #Array de 10 elementos que va de 10 en 10
a

array([  10.,   20.,   30.,   40.,   50.,   60.,   70.,   80.,   90.,  100.])

In [137]:
b = numpy.array( [1,2,3] )
b

array([1, 2, 3])

In [138]:
a.shape # Here a is 1-dimensional

(10, 1)

In [139]:
b.shape

(3,)

In [140]:
a+b #No tiene el mismo tamaño

array([[  11.,   12.,   13.],
       [  21.,   22.,   23.],
       [  31.,   32.,   33.],
       [  41.,   42.,   43.],
       [  51.,   52.,   53.],
       [  61.,   62.,   63.],
       [  71.,   72.,   73.],
       [  81.,   82.,   83.],
       [  91.,   92.,   93.],
       [ 101.,  102.,  103.]])

In [141]:
a[:,numpy.newaxis]+b 
#Añade una dimensión y replica los valores de A y suma los valores de B, suma 1 en la primera columna, 2 en la segunda, y suma 3 en la tercera columna
#Si modificamos B a [1,2,3,4], creará una nueva columna y sumará 4

array([[[  11.,   12.,   13.]],

       [[  21.,   22.,   23.]],

       [[  31.,   32.,   33.]],

       [[  41.,   42.,   43.]],

       [[  51.,   52.,   53.]],

       [[  61.,   62.,   63.]],

       [[  71.,   72.,   73.]],

       [[  81.,   82.,   83.]],

       [[  91.,   92.,   93.]],

       [[ 101.,  102.,  103.]]])

In [143]:
a = a.reshape( len(a), 1 ) #Ha creado una matriz de 10 filas x 1 columna
a

array([[  10.],
       [  20.],
       [  30.],
       [  40.],
       [  50.],
       [  60.],
       [  70.],
       [  80.],
       [  90.],
       [ 100.]])

In [144]:
a.shape # Here a is 2-dimensional

(10, 1)

In [145]:
a+b

array([[  11.,   12.,   13.],
       [  21.,   22.,   23.],
       [  31.,   32.,   33.],
       [  41.,   42.,   43.],
       [  51.,   52.,   53.],
       [  61.,   62.,   63.],
       [  71.,   72.,   73.],
       [  81.,   82.,   83.],
       [  91.,   92.,   93.],
       [ 101.,  102.,  103.]])